server:
  port: ${SERVER_PORT:8093}

spring:
  datasource:

    url: jdbc:mysql://${DB_SERVER:127.0.0.1}:${DB_PORT:3306}/${DB_NAME:collect-manage}?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=${DB_TIMEZONE:Asia/Shanghai}
    username: ${DB_USER:root}
    password: ${DB_PWD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: user_hikari
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  data:
    mongodb:
      host: ${MONGODB_HOST:127.0.0.1}
      port: ${MONGODB_PORT:27017}
      username: ${MONGODB_USERNAME:admin}
      password: ${MONGODB_PWD:root}
      database: Repo_history
      authentication-database: admin
  redis:
    host: ${REDIS_SERVER:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PWD:root}
    database: ${REDIS_DATABASE:2}
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 10000
      shutdown-timeout: 100

custom:
  mqtt:
    urls: ${MQTT_URL:tcp://mqtt.dev1.zdiai.net:8883}
    username: ${MQTT_USER:mqtt}
    password: ${MQTT_PWD:root}
    keepAlive: 60
    customer:
      clientIdPrefix: ${MQTT_CUSTOM_CLIENTID_PERFIX:mqttConsumer}
      # 订阅的主题，可以订阅多个Topic，逗号分隔
      topics: ${MQTT_CUSTOM_TOPIC:dev1metadata,dev1seriesdata}
      # 服务质量参数
      qos: ${MQTT_CUSTOM_QOS:1}
      completionTimeout: ${MQTT_COMPLETION_TIMEOUT:30000}